#ifndef MSGS_H
#define MSGS_H

// alphabetical ordered:
#define ACCPERR "Sock: Accept error "
#define BINDERR "Sock: Bind error "
#define HTTPDREP "Chat: Using replacement strings"
#define HTTPDDOP "Chat: Default operator login "
#define CFILEOK "Parsing config file"
#define CFILEFA "Failed opening config file!"
#define CONTACT "Contact: http://www.yhttpd.org, Mail@yhttpd.org, ICQ: 11655527"
#define CLRHTML "HTML: Cleared the template cache "
#define CLIWELC "Command Line Interface (type help for a list of all commands)"
#define CLIPRMO ">> "
#define CLIPRMI "<< "
#define CLIHELP "Unknown command (use help)"
#define CLIMSQL "Spawing system mysql client (enter exit to return)"
#define CLISHEL "Spawing system shell (enter exit to return)"
#define DATAADD "Data: Adding used connection into the queue"
#define DATADIS "Data: Closing all connections"
#define DATADI2 "Data: Closing idle connection ("
#define DATAQUE "Data: "
#define DATAGET "Data: Using database connection queue "
#define DATAIN0 "Data: Initializing maxcon to "
#define DATAIN1 "Data: Initializing mincon to "
#define DATAMAX "Data: Max database connections reached "
#define DATAMA0 "Data: Max database connections "
#define DATANEW "Data: Creating new database conbbnection "
#define DESCRIP "Copyright (C) 2003 Paul C. Buetow, Volker Richter"
#define DESCRI2 "Copyright (C) 2004 Paul C. Buetow"
#define DONEMSG "done"
#define DOWNMSG "Shutting down "
#define GARBAGE "Garbage: Initializing collector "
#define GARBACT "Garbage collector activated "
#define GAROFFNE "Garbage: No garbage to remove available "
#define GARROOM "Garbage: Added room "
#define GARUSER "Garbage: Added user "
#define GARUSE2 "Garbage: Recycle user "
#define LISTERR "Sock: Listen error "
#define LOGERR1 "Logging: Could not open logfile "
#define LOGERR2 "Logging: No filename specified "
#define LOGINER "Chat: Login failed (password), nick: "
#define LOGINE0 "Chat: Login failed (empty nick)"
#define LOGINE1 "Chat: Login failed (alpha nick), nick: "
#define LOGINE2 "Chat: Login failed (nick length), nick: "
#define LOGINE3 "Chat: Login failed (room length), nick/room: "
#define MODULEC "Modl: Caching "
#define MODULER "Modl: Requesting "
#define MODUNLO "Modl: Unloading all modules "
#define MODRELO "Modl: Reloading all modules "
#ifdef DATABASE
#define MYSQLQU "MySQL: " 
#define MYSQLQ2 "MySQL: Adding query " 
#define MYSQLE1 "MySQL: Error running mysql_init "
#endif
#define NCURADM "ADMINISTRATOR's MAIN MENU"
#define NCURMSG "SERVER SYSTEM MESSAGES"
#define NEWREQU "Sock: New request "
#define NEWROOM "Chat: New room "
#define NEWUSER "Chat: New user "
#define OFFFOUND "HTML: File not found "
#define PERMSTD "Reading standard command exec permissions"
#define POOLERR "Pool: Malloc error "
#define READERR "Sock: Read error "
#define REMROOM "Garbage: Removing room "
#define REMUSER "Garbage: Removing user "
#define REQUEST "Reqp: Request string "
#define SELCERR "Sock: Select error "
#define SEPERAT "-----------------------"
#define SESSION "Session: Count "
#define SESSDMP "Session: Dump of session"
#define SHELLER "Shell: Could not execute command"
#define SHELLEX "Shell: Executing the following command:"
#define STATUPR "Stats: Updated rusage history"
#define STATRSS "Stats: Max resident set size "
#define REUROOM "Garbage: Reusing room object "
#define SOCKCLN "Sock: Initializing a client socket at "
#define SOCKCON "Sock: Connecting to "
#define SOCKCRT "Sock: Created socket on "
#define SOCKSRV "Sock: Initializing server socket "
#define SOCKERR "Sock: Can't create socket, trying next port "
#define SOCKER2 "Sock: Unknown hostname "
#define SOCKRDY "Sock: Server socket is ready "
#define SSLINIT "SSL: Initializing OpenSSL"
#define TECACHE "HTML: Caching template "
#define THRDSTR "Thread: Running"
#define TIMERAT "Timer: User autoaway timeout "
#define TIMERIN "Timer: Initializing "
#define TIMEROF "Timer: Setting offset to "
#define TIMERTH "Timer: Starting timer thread "
#define TIMERTO "Timer: User logout timeout "
#define TIMERUP "Timer: System uptime "
#define XMLREAD "XML: Reading "
#define XMLERR "XML Error: "
#define XMLER1 "XML Error: Unable to load file "
#define VERSION "yhttpd 0.7"
#define BRANCH "RELEASE"
#define BUILDNR 2798
#define UNAME "FreeBSD 5.2.1-RELEASE-p10 i386"

#endif
